mysql:
  path: 127.0.0.1
  port: 3306
  dbname: admindb
  config: charset=utf8mb4&parseTime=True&loc=Local
  username: weizhifeng
  password: weizhifeng10
  max-idle-conns: 0
  max-open-conns: 0
  logmode:
  logzap: true